name: Example - Docker action

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: greet
        uses: ./modules/10-custom-actions/docker-action
        with:
          who-to-greet: TaskFlow
      - run: echo "${{ steps.greet.outputs.greeting }}"
